ALTER TABLE SPECTATEUR DROP CONSTRAINT FK_SPECTATEUR_NumAcheteur;
ALTER TABLE SPECTATEUR DROP CONSTRAINT FK_SPECTATEUR_NumEv;
ALTER TABLE APPLIQUE DROP CONSTRAINT FK_APPLIQUE_NumEv;
ALTER TABLE APPLIQUE DROP CONSTRAINT FK_APPLIQUE_id;


DROP TABLE tarif CASCADE CONSTRAINTS;
DROP TABLE evenement;
DROP TABLE acheteur;
DROP TABLE spectateur;