CREATE TABLE jury (
numero INTEGER PRIMARY KEY,
nom VARCHAR(40),
prenom VARCHAR(40),
moyS1 NUMBER(3,3),
moyS2 NUMBER(3,3),
TP INTEGER,
Responsable VARCHAR(40),
Delegue VARCHAR(40),
Entreprise VARCHAR(40),
Lieu VARCHAR(40))